export const quizData = [
    {
      id: 1,
      type: "multipleChoice",
      category: "General Knowledge",
      difficulty: "Easy",
      points: 1,
      question: "Which planet is closest to the Sun?",
      options: ["Venus", "Mercury", "Earth", "Mars"],
      correctAnswer: "Mercury",
      explanation: "Mercury is the closest planet to the Sun.",
    },{
        id: 2,
        type: "multipleChoice",
        category: "Computer science",
        difficulty: "Medium",
        points: 1,
        question: "Which data structure organizes items in a First-In, First-Out (FIFO) manner?",
        options: ["Stack", "Queue", "Tree", "Graph"],
        correctAnswer: "Queue",
        explanation: "Queue is a linear data structure that follows the FIFO principle.",
    },{
        id: 3,
        type: "multipleChoice",
        category: "Computer science",
        difficulty: "Medium",
        points: 1,
        question: "Which of the following is primarily used for structuring web pages?",
        options: ["Python", "Java", "HTML", "C++"],
        correctAnswer: "HTML",
        explanation: "HTML (HyperText Markup Language) is the standard markup language for creating web pages.",
    },{
        id: 4,
        type: "multipleChoice",
        category: "Science",
        difficulty: "Medium",
        points: 1,
        question: "Which chemical symbol stands for Gold?",
        options: ["Au", "Gd", "Ag", "Pt"],
        correctAnswer: "Au",
        explanation: "The chemical symbol for Gold is Au.",
    },{
        id: 5,
        type: "multipleChoice",
        category: "Science",
        difficulty: "Medium",
        points: 1,
        question: "Which of these processes is not typically involved in refining petroleum?",
        options: ["Fractional distillation", "Cracking", "Polymerization", "Filtration"],
        correctAnswer: "Filtration",
        explanation: "Filtration is not a common process in petroleum refining.",
    },{
        id: 6,
        type: "numericalType",
        category: "Maths",
        difficulty: "Medium",
        points: 1,
        question: "What is the value of 12 + 28?",
        correctAnswer: "40",
        explanation: "12 + 28 = 40",
    },{
        id: 7,
        type: "numericalType",
        category: "General Knowledge",
        difficulty: "Easy",
        points: 1,
        question: "How many states are there in the United States?",
        correctAnswer: "50",
        explanation: "There are 50 states in the United States.",
    },{
        id: 8,
        type: "numericalType",
        category: "General Knowledge",
        difficulty: "Medium",
        points: 1,
        question: "In which year was the Declaration of Independence signed?",
        correctAnswer: "1776",
        explanation: "The Declaration of Independence was signed in 1776.",
    },{
        id: 9,
        type: "numericalType",
        category: "Maths",
        difficulty: "Medium",
        points: 1,
        question: "What is the value of pi rounded to the nearest integer?",
        correctAnswer: "3",
        explanation: "The value of pi rounded to the nearest integer is 3.",
    },{
        id: 10,
        type: "numericalType",
        category: "Science",
        difficulty: "Medium",
        points: 1,
        question: "If a car travels at 60 mph for 2 hours, how many miles does it travel?",
        correctAnswer: "120",
        explanation: "Distance = Speed x Time = 60 x 2 = 120 miles.",
    }
];